sudo: required
language: go
go:
- "1.10"
services:
- docker
deploy:
  provider: releases
  api_key: dc41949f2db5ea244c428b23cb8b43ff30508518
  script:
    echo "Tag:$TRAVIS_TAG-Commit:$TRAVIS_COMMIT"
  on:
    branch: master
    tags: true
