sudo: required
language: go
go:
- "1.10"
services:
- docker
deploy:
  provider: releases
  api_key: 78443e2c9c78abf778921952594d84d938b509c7
  script:
    echo "Tag:$TRAVIS_TAG-Commit:$TRAVIS_COMMIT"
  on:
    branch: master
    tags: true
